# Generated by Django 4.2.20 on 2025-05-19 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="职位标题")),
                ("company", models.CharField(max_length=200, verbose_name="公司名称")),
                ("description", models.TextField(verbose_name="职位描述")),
                ("requirements", models.TextField(verbose_name="职位要求")),
                (
                    "salary_min",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="最低薪资"
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="最高薪资"
                    ),
                ),
                ("location", models.CharField(max_length=100, verbose_name="工作地点")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否有效")),
            ],
            options={
                "verbose_name": "职位",
                "verbose_name_plural": "职位",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="类别名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="类别描述"),
                ),
            ],
            options={
                "verbose_name": "职位类别",
                "verbose_name_plural": "职位类别",
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resume", models.FileField(upload_to="resumes/", verbose_name="简历")),
                (
                    "cover_letter",
                    models.TextField(blank=True, null=True, verbose_name="求职信"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("reviewing", "审核中"),
                            ("interviewed", "已面试"),
                            ("offered", "已录用"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="job_recommendation.job",
                        verbose_name="申请职位",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请者",
                    ),
                ),
            ],
            options={
                "verbose_name": "职位申请",
                "verbose_name_plural": "职位申请",
                "ordering": ["-applied_at"],
            },
        ),
        migrations.AddField(
            model_name="job",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="job_recommendation.jobcategory",
                verbose_name="职位类别",
            ),
        ),
    ]
