# Generated by Django 4.2.20 on 2025-05-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_recommendation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="education",
            field=models.CharField(
                choices=[
                    ("any", "学历不限"),
                    ("college", "大专"),
                    ("bachelor", "本科"),
                    ("master", "硕士"),
                    ("phd", "博士"),
                ],
                default="any",
                max_length=20,
                verbose_name="学历要求",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="experience",
            field=models.CharField(
                choices=[
                    ("any", "经验不限"),
                    ("0-3", "3年及以下"),
                    ("3-5", "3-5年"),
                    ("5-10", "5-10年"),
                    ("10+", "10年以上"),
                ],
                default="any",
                max_length=20,
                verbose_name="经验要求",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="payment_cycle",
            field=models.CharField(
                choices=[
                    ("hourly", "时薪"),
                    ("daily", "日薪"),
                    ("monthly", "月薪"),
                    ("project", "项目计价"),
                ],
                default="monthly",
                max_length=20,
                verbose_name="薪资周期",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="tags",
            field=models.JSONField(blank=True, default=list, verbose_name="职位标签"),
        ),
        migrations.AddField(
            model_name="job",
            name="urgency",
            field=models.CharField(
                choices=[("normal", "普通"), ("urgent", "紧急"), ("very-urgent", "非常紧急")],
                default="normal",
                max_length=20,
                verbose_name="紧急程度",
            ),
        ),
    ]
