# Generated by Django 4.2.20 on 2025-05-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "job_recommendation",
            "0002_job_education_job_experience_job_payment_cycle_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="tags",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="职位标签"
            ),
        ),
    ]
