# Generated by Django 4.2.20 on 2025-05-26 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("job_recommendation", "0003_alter_job_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="publisher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="published_jobs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="发布者",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="resume",
            field=models.FileField(
                blank=True, null=True, upload_to="resumes/", verbose_name="简历"
            ),
        ),
    ]
