# Generated by Django 4.2.20 on 2025-05-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("freelancer", "自由职业者"), ("employer", "雇主"), ("admin", "管理员")],
                default="freelancer",
                max_length=20,
                verbose_name="用户角色",
            ),
        ),
    ]
