# Generated by Django 4.2.20 on 2025-05-20 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0002_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="企业名称")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="company/logos/",
                        verbose_name="企业Logo",
                    ),
                ),
                ("industry", models.CharField(max_length=50, verbose_name="所属行业")),
                ("address", models.CharField(max_length=200, verbose_name="企业地址")),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("少于50人", "少于50人"),
                            ("50-200人", "50-200人"),
                            ("200-500人", "200-500人"),
                            ("500-1000人", "500-1000人"),
                            ("1000人以上", "1000人以上"),
                        ],
                        max_length=20,
                        verbose_name="企业规模",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="企业简介"),
                ),
                (
                    "verify_status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("verified", "已认证"),
                            ("rejected", "未通过"),
                            ("unverified", "未认证"),
                        ],
                        default="unverified",
                        max_length=20,
                        verbose_name="验证状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "企业信息",
                "verbose_name_plural": "企业信息",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="credit_score",
            field=models.IntegerField(default=80, verbose_name="信誉分"),
        ),
        migrations.CreateModel(
            name="UserExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="职位名称")),
                ("company", models.CharField(max_length=100, verbose_name="公司名称")),
                ("start_date", models.DateField(verbose_name="开始日期")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="结束日期"),
                ),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="是否为当前工作"),
                ),
                ("description", models.TextField(verbose_name="工作描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作经历",
                "verbose_name_plural": "工作经历",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="UserCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="证书名称")),
                ("issue_date", models.DateField(verbose_name="发证日期")),
                (
                    "certificate_file",
                    models.FileField(upload_to="certificates/", verbose_name="证书文件"),
                ),
                (
                    "verify_status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("verified", "已验证"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="验证状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户证书",
                "verbose_name_plural": "用户证书",
            },
        ),
        migrations.CreateModel(
            name="RecruitmentPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "positions",
                    models.TextField(help_text="逗号分隔的职位列表", verbose_name="偏好职位类型"),
                ),
                (
                    "locations",
                    models.TextField(help_text="逗号分隔的地点列表", verbose_name="工作地点"),
                ),
                ("salary_min", models.IntegerField(default=0, verbose_name="最低薪资")),
                ("salary_max", models.IntegerField(default=0, verbose_name="最高薪资")),
                (
                    "requirements",
                    models.TextField(blank=True, null=True, verbose_name="其他要求"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruitment_preference",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "招聘偏好",
                "verbose_name_plural": "招聘偏好",
            },
        ),
        migrations.CreateModel(
            name="IdentityVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("real_name", models.CharField(max_length=50, verbose_name="真实姓名")),
                ("id_number", models.CharField(max_length=18, verbose_name="身份证号码")),
                (
                    "id_front",
                    models.ImageField(
                        upload_to="identity/front/", verbose_name="身份证正面"
                    ),
                ),
                (
                    "id_back",
                    models.ImageField(upload_to="identity/back/", verbose_name="身份证背面"),
                ),
                (
                    "verify_status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("verified", "已验证"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="验证状态",
                    ),
                ),
                (
                    "verify_message",
                    models.TextField(blank=True, null=True, verbose_name="审核消息"),
                ),
                (
                    "submit_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "verify_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="验证时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity_verification",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "实名认证",
                "verbose_name_plural": "实名认证",
            },
        ),
        migrations.CreateModel(
            name="CompanyCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="证书名称")),
                ("issue_date", models.DateField(verbose_name="发证日期")),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="到期日期"),
                ),
                (
                    "certificate_file",
                    models.FileField(
                        upload_to="company/certificates/", verbose_name="证书文件"
                    ),
                ),
                (
                    "verify_status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("verified", "已验证"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="验证状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="user_management.company",
                        verbose_name="企业",
                    ),
                ),
            ],
            options={
                "verbose_name": "企业资质证书",
                "verbose_name_plural": "企业资质证书",
            },
        ),
        migrations.AddField(
            model_name="company",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
    ]
